source 'http://rubygems.org'

gem 'sinatra', '~> 1.3.2'
gem 'sequel', '~> 3.45.0'
gem 'haml'
gem 'log4r'

group :development, :test do
  gem 'sqlite3'
end

group :production do
  #  gem 'pg'
  gem 'sqlite3'
end
